# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/seb/.bin/clion-2018.1.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/seb/.bin/clion-2018.1.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seb/Client

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seb/Client

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/seb/.bin/clion-2018.1.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/seb/.bin/clion-2018.1.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seb/Client/CMakeFiles /home/seb/Client/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seb/Client/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

libs/Json/srcs/Entity/Entity.o: libs/Json/srcs/Entity/Entity.cpp.o

.PHONY : libs/Json/srcs/Entity/Entity.o

# target to build an object file
libs/Json/srcs/Entity/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/srcs/Entity/Entity.cpp.o
.PHONY : libs/Json/srcs/Entity/Entity.cpp.o

libs/Json/srcs/Entity/Entity.i: libs/Json/srcs/Entity/Entity.cpp.i

.PHONY : libs/Json/srcs/Entity/Entity.i

# target to preprocess a source file
libs/Json/srcs/Entity/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/srcs/Entity/Entity.cpp.i
.PHONY : libs/Json/srcs/Entity/Entity.cpp.i

libs/Json/srcs/Entity/Entity.s: libs/Json/srcs/Entity/Entity.cpp.s

.PHONY : libs/Json/srcs/Entity/Entity.s

# target to generate assembly for a file
libs/Json/srcs/Entity/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/srcs/Entity/Entity.cpp.s
.PHONY : libs/Json/srcs/Entity/Entity.cpp.s

libs/Json/srcs/Parser/Parser.o: libs/Json/srcs/Parser/Parser.cpp.o

.PHONY : libs/Json/srcs/Parser/Parser.o

# target to build an object file
libs/Json/srcs/Parser/Parser.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/srcs/Parser/Parser.cpp.o
.PHONY : libs/Json/srcs/Parser/Parser.cpp.o

libs/Json/srcs/Parser/Parser.i: libs/Json/srcs/Parser/Parser.cpp.i

.PHONY : libs/Json/srcs/Parser/Parser.i

# target to preprocess a source file
libs/Json/srcs/Parser/Parser.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/srcs/Parser/Parser.cpp.i
.PHONY : libs/Json/srcs/Parser/Parser.cpp.i

libs/Json/srcs/Parser/Parser.s: libs/Json/srcs/Parser/Parser.cpp.s

.PHONY : libs/Json/srcs/Parser/Parser.s

# target to generate assembly for a file
libs/Json/srcs/Parser/Parser.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/srcs/Parser/Parser.cpp.s
.PHONY : libs/Json/srcs/Parser/Parser.cpp.s

libs/Json/tests/Entity/main.o: libs/Json/tests/Entity/main.cpp.o

.PHONY : libs/Json/tests/Entity/main.o

# target to build an object file
libs/Json/tests/Entity/main.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/tests/Entity/main.cpp.o
.PHONY : libs/Json/tests/Entity/main.cpp.o

libs/Json/tests/Entity/main.i: libs/Json/tests/Entity/main.cpp.i

.PHONY : libs/Json/tests/Entity/main.i

# target to preprocess a source file
libs/Json/tests/Entity/main.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/tests/Entity/main.cpp.i
.PHONY : libs/Json/tests/Entity/main.cpp.i

libs/Json/tests/Entity/main.s: libs/Json/tests/Entity/main.cpp.s

.PHONY : libs/Json/tests/Entity/main.s

# target to generate assembly for a file
libs/Json/tests/Entity/main.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/tests/Entity/main.cpp.s
.PHONY : libs/Json/tests/Entity/main.cpp.s

libs/Json/tests/Parser/main.o: libs/Json/tests/Parser/main.cpp.o

.PHONY : libs/Json/tests/Parser/main.o

# target to build an object file
libs/Json/tests/Parser/main.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/tests/Parser/main.cpp.o
.PHONY : libs/Json/tests/Parser/main.cpp.o

libs/Json/tests/Parser/main.i: libs/Json/tests/Parser/main.cpp.i

.PHONY : libs/Json/tests/Parser/main.i

# target to preprocess a source file
libs/Json/tests/Parser/main.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/tests/Parser/main.cpp.i
.PHONY : libs/Json/tests/Parser/main.cpp.i

libs/Json/tests/Parser/main.s: libs/Json/tests/Parser/main.cpp.s

.PHONY : libs/Json/tests/Parser/main.s

# target to generate assembly for a file
libs/Json/tests/Parser/main.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/Json/tests/Parser/main.cpp.s
.PHONY : libs/Json/tests/Parser/main.cpp.s

libs/SmartEvent/srcs/Event/Event.o: libs/SmartEvent/srcs/Event/Event.cpp.o

.PHONY : libs/SmartEvent/srcs/Event/Event.o

# target to build an object file
libs/SmartEvent/srcs/Event/Event.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/srcs/Event/Event.cpp.o
.PHONY : libs/SmartEvent/srcs/Event/Event.cpp.o

libs/SmartEvent/srcs/Event/Event.i: libs/SmartEvent/srcs/Event/Event.cpp.i

.PHONY : libs/SmartEvent/srcs/Event/Event.i

# target to preprocess a source file
libs/SmartEvent/srcs/Event/Event.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/srcs/Event/Event.cpp.i
.PHONY : libs/SmartEvent/srcs/Event/Event.cpp.i

libs/SmartEvent/srcs/Event/Event.s: libs/SmartEvent/srcs/Event/Event.cpp.s

.PHONY : libs/SmartEvent/srcs/Event/Event.s

# target to generate assembly for a file
libs/SmartEvent/srcs/Event/Event.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/srcs/Event/Event.cpp.s
.PHONY : libs/SmartEvent/srcs/Event/Event.cpp.s

libs/SmartEvent/srcs/HdlCollector/HdlCollector.o: libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.o

.PHONY : libs/SmartEvent/srcs/HdlCollector/HdlCollector.o

# target to build an object file
libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.o
.PHONY : libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.o

libs/SmartEvent/srcs/HdlCollector/HdlCollector.i: libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.i

.PHONY : libs/SmartEvent/srcs/HdlCollector/HdlCollector.i

# target to preprocess a source file
libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.i
.PHONY : libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.i

libs/SmartEvent/srcs/HdlCollector/HdlCollector.s: libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.s

.PHONY : libs/SmartEvent/srcs/HdlCollector/HdlCollector.s

# target to generate assembly for a file
libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.s
.PHONY : libs/SmartEvent/srcs/HdlCollector/HdlCollector.cpp.s

libs/SmartEvent/tests/Event/main.o: libs/SmartEvent/tests/Event/main.cpp.o

.PHONY : libs/SmartEvent/tests/Event/main.o

# target to build an object file
libs/SmartEvent/tests/Event/main.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/tests/Event/main.cpp.o
.PHONY : libs/SmartEvent/tests/Event/main.cpp.o

libs/SmartEvent/tests/Event/main.i: libs/SmartEvent/tests/Event/main.cpp.i

.PHONY : libs/SmartEvent/tests/Event/main.i

# target to preprocess a source file
libs/SmartEvent/tests/Event/main.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/tests/Event/main.cpp.i
.PHONY : libs/SmartEvent/tests/Event/main.cpp.i

libs/SmartEvent/tests/Event/main.s: libs/SmartEvent/tests/Event/main.cpp.s

.PHONY : libs/SmartEvent/tests/Event/main.s

# target to generate assembly for a file
libs/SmartEvent/tests/Event/main.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/tests/Event/main.cpp.s
.PHONY : libs/SmartEvent/tests/Event/main.cpp.s

libs/SmartEvent/tests/HdlCollector/main.o: libs/SmartEvent/tests/HdlCollector/main.cpp.o

.PHONY : libs/SmartEvent/tests/HdlCollector/main.o

# target to build an object file
libs/SmartEvent/tests/HdlCollector/main.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/tests/HdlCollector/main.cpp.o
.PHONY : libs/SmartEvent/tests/HdlCollector/main.cpp.o

libs/SmartEvent/tests/HdlCollector/main.i: libs/SmartEvent/tests/HdlCollector/main.cpp.i

.PHONY : libs/SmartEvent/tests/HdlCollector/main.i

# target to preprocess a source file
libs/SmartEvent/tests/HdlCollector/main.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/tests/HdlCollector/main.cpp.i
.PHONY : libs/SmartEvent/tests/HdlCollector/main.cpp.i

libs/SmartEvent/tests/HdlCollector/main.s: libs/SmartEvent/tests/HdlCollector/main.cpp.s

.PHONY : libs/SmartEvent/tests/HdlCollector/main.s

# target to generate assembly for a file
libs/SmartEvent/tests/HdlCollector/main.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/libs/SmartEvent/tests/HdlCollector/main.cpp.s
.PHONY : libs/SmartEvent/tests/HdlCollector/main.cpp.s

srcs/ECS/Entity/Entity.o: srcs/ECS/Entity/Entity.cpp.o

.PHONY : srcs/ECS/Entity/Entity.o

# target to build an object file
srcs/ECS/Entity/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/ECS/Entity/Entity.cpp.o
.PHONY : srcs/ECS/Entity/Entity.cpp.o

srcs/ECS/Entity/Entity.i: srcs/ECS/Entity/Entity.cpp.i

.PHONY : srcs/ECS/Entity/Entity.i

# target to preprocess a source file
srcs/ECS/Entity/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/ECS/Entity/Entity.cpp.i
.PHONY : srcs/ECS/Entity/Entity.cpp.i

srcs/ECS/Entity/Entity.s: srcs/ECS/Entity/Entity.cpp.s

.PHONY : srcs/ECS/Entity/Entity.s

# target to generate assembly for a file
srcs/ECS/Entity/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/ECS/Entity/Entity.cpp.s
.PHONY : srcs/ECS/Entity/Entity.cpp.s

srcs/Graphical/EventReceiver.o: srcs/Graphical/EventReceiver.cpp.o

.PHONY : srcs/Graphical/EventReceiver.o

# target to build an object file
srcs/Graphical/EventReceiver.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/EventReceiver.cpp.o
.PHONY : srcs/Graphical/EventReceiver.cpp.o

srcs/Graphical/EventReceiver.i: srcs/Graphical/EventReceiver.cpp.i

.PHONY : srcs/Graphical/EventReceiver.i

# target to preprocess a source file
srcs/Graphical/EventReceiver.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/EventReceiver.cpp.i
.PHONY : srcs/Graphical/EventReceiver.cpp.i

srcs/Graphical/EventReceiver.s: srcs/Graphical/EventReceiver.cpp.s

.PHONY : srcs/Graphical/EventReceiver.s

# target to generate assembly for a file
srcs/Graphical/EventReceiver.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/EventReceiver.cpp.s
.PHONY : srcs/Graphical/EventReceiver.cpp.s

srcs/Graphical/SystemCreateDeletableWall.o: srcs/Graphical/SystemCreateDeletableWall.cpp.o

.PHONY : srcs/Graphical/SystemCreateDeletableWall.o

# target to build an object file
srcs/Graphical/SystemCreateDeletableWall.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateDeletableWall.cpp.o
.PHONY : srcs/Graphical/SystemCreateDeletableWall.cpp.o

srcs/Graphical/SystemCreateDeletableWall.i: srcs/Graphical/SystemCreateDeletableWall.cpp.i

.PHONY : srcs/Graphical/SystemCreateDeletableWall.i

# target to preprocess a source file
srcs/Graphical/SystemCreateDeletableWall.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateDeletableWall.cpp.i
.PHONY : srcs/Graphical/SystemCreateDeletableWall.cpp.i

srcs/Graphical/SystemCreateDeletableWall.s: srcs/Graphical/SystemCreateDeletableWall.cpp.s

.PHONY : srcs/Graphical/SystemCreateDeletableWall.s

# target to generate assembly for a file
srcs/Graphical/SystemCreateDeletableWall.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateDeletableWall.cpp.s
.PHONY : srcs/Graphical/SystemCreateDeletableWall.cpp.s

srcs/Graphical/SystemCreateMap.o: srcs/Graphical/SystemCreateMap.cpp.o

.PHONY : srcs/Graphical/SystemCreateMap.o

# target to build an object file
srcs/Graphical/SystemCreateMap.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateMap.cpp.o
.PHONY : srcs/Graphical/SystemCreateMap.cpp.o

srcs/Graphical/SystemCreateMap.i: srcs/Graphical/SystemCreateMap.cpp.i

.PHONY : srcs/Graphical/SystemCreateMap.i

# target to preprocess a source file
srcs/Graphical/SystemCreateMap.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateMap.cpp.i
.PHONY : srcs/Graphical/SystemCreateMap.cpp.i

srcs/Graphical/SystemCreateMap.s: srcs/Graphical/SystemCreateMap.cpp.s

.PHONY : srcs/Graphical/SystemCreateMap.s

# target to generate assembly for a file
srcs/Graphical/SystemCreateMap.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateMap.cpp.s
.PHONY : srcs/Graphical/SystemCreateMap.cpp.s

srcs/Graphical/SystemCreatePlayer.o: srcs/Graphical/SystemCreatePlayer.cpp.o

.PHONY : srcs/Graphical/SystemCreatePlayer.o

# target to build an object file
srcs/Graphical/SystemCreatePlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreatePlayer.cpp.o
.PHONY : srcs/Graphical/SystemCreatePlayer.cpp.o

srcs/Graphical/SystemCreatePlayer.i: srcs/Graphical/SystemCreatePlayer.cpp.i

.PHONY : srcs/Graphical/SystemCreatePlayer.i

# target to preprocess a source file
srcs/Graphical/SystemCreatePlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreatePlayer.cpp.i
.PHONY : srcs/Graphical/SystemCreatePlayer.cpp.i

srcs/Graphical/SystemCreatePlayer.s: srcs/Graphical/SystemCreatePlayer.cpp.s

.PHONY : srcs/Graphical/SystemCreatePlayer.s

# target to generate assembly for a file
srcs/Graphical/SystemCreatePlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreatePlayer.cpp.s
.PHONY : srcs/Graphical/SystemCreatePlayer.cpp.s

srcs/Graphical/SystemCreateWall.o: srcs/Graphical/SystemCreateWall.cpp.o

.PHONY : srcs/Graphical/SystemCreateWall.o

# target to build an object file
srcs/Graphical/SystemCreateWall.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateWall.cpp.o
.PHONY : srcs/Graphical/SystemCreateWall.cpp.o

srcs/Graphical/SystemCreateWall.i: srcs/Graphical/SystemCreateWall.cpp.i

.PHONY : srcs/Graphical/SystemCreateWall.i

# target to preprocess a source file
srcs/Graphical/SystemCreateWall.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateWall.cpp.i
.PHONY : srcs/Graphical/SystemCreateWall.cpp.i

srcs/Graphical/SystemCreateWall.s: srcs/Graphical/SystemCreateWall.cpp.s

.PHONY : srcs/Graphical/SystemCreateWall.s

# target to generate assembly for a file
srcs/Graphical/SystemCreateWall.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemCreateWall.cpp.s
.PHONY : srcs/Graphical/SystemCreateWall.cpp.s

srcs/Graphical/SystemEventManager.o: srcs/Graphical/SystemEventManager.cpp.o

.PHONY : srcs/Graphical/SystemEventManager.o

# target to build an object file
srcs/Graphical/SystemEventManager.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemEventManager.cpp.o
.PHONY : srcs/Graphical/SystemEventManager.cpp.o

srcs/Graphical/SystemEventManager.i: srcs/Graphical/SystemEventManager.cpp.i

.PHONY : srcs/Graphical/SystemEventManager.i

# target to preprocess a source file
srcs/Graphical/SystemEventManager.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemEventManager.cpp.i
.PHONY : srcs/Graphical/SystemEventManager.cpp.i

srcs/Graphical/SystemEventManager.s: srcs/Graphical/SystemEventManager.cpp.s

.PHONY : srcs/Graphical/SystemEventManager.s

# target to generate assembly for a file
srcs/Graphical/SystemEventManager.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemEventManager.cpp.s
.PHONY : srcs/Graphical/SystemEventManager.cpp.s

srcs/Graphical/SystemUpdateDeplacement.o: srcs/Graphical/SystemUpdateDeplacement.cpp.o

.PHONY : srcs/Graphical/SystemUpdateDeplacement.o

# target to build an object file
srcs/Graphical/SystemUpdateDeplacement.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemUpdateDeplacement.cpp.o
.PHONY : srcs/Graphical/SystemUpdateDeplacement.cpp.o

srcs/Graphical/SystemUpdateDeplacement.i: srcs/Graphical/SystemUpdateDeplacement.cpp.i

.PHONY : srcs/Graphical/SystemUpdateDeplacement.i

# target to preprocess a source file
srcs/Graphical/SystemUpdateDeplacement.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemUpdateDeplacement.cpp.i
.PHONY : srcs/Graphical/SystemUpdateDeplacement.cpp.i

srcs/Graphical/SystemUpdateDeplacement.s: srcs/Graphical/SystemUpdateDeplacement.cpp.s

.PHONY : srcs/Graphical/SystemUpdateDeplacement.s

# target to generate assembly for a file
srcs/Graphical/SystemUpdateDeplacement.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Graphical/SystemUpdateDeplacement.cpp.s
.PHONY : srcs/Graphical/SystemUpdateDeplacement.cpp.s

srcs/Main.o: srcs/Main.cpp.o

.PHONY : srcs/Main.o

# target to build an object file
srcs/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Main.cpp.o
.PHONY : srcs/Main.cpp.o

srcs/Main.i: srcs/Main.cpp.i

.PHONY : srcs/Main.i

# target to preprocess a source file
srcs/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Main.cpp.i
.PHONY : srcs/Main.cpp.i

srcs/Main.s: srcs/Main.cpp.s

.PHONY : srcs/Main.s

# target to generate assembly for a file
srcs/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/srcs/Main.cpp.s
.PHONY : srcs/Main.cpp.s

tests/basicECS/Main.o: tests/basicECS/Main.cpp.o

.PHONY : tests/basicECS/Main.o

# target to build an object file
tests/basicECS/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/tests/basicECS/Main.cpp.o
.PHONY : tests/basicECS/Main.cpp.o

tests/basicECS/Main.i: tests/basicECS/Main.cpp.i

.PHONY : tests/basicECS/Main.i

# target to preprocess a source file
tests/basicECS/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/tests/basicECS/Main.cpp.i
.PHONY : tests/basicECS/Main.cpp.i

tests/basicECS/Main.s: tests/basicECS/Main.cpp.s

.PHONY : tests/basicECS/Main.s

# target to generate assembly for a file
tests/basicECS/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/tests/basicECS/Main.cpp.s
.PHONY : tests/basicECS/Main.cpp.s

tests/graphicalTest/test.o: tests/graphicalTest/test.cpp.o

.PHONY : tests/graphicalTest/test.o

# target to build an object file
tests/graphicalTest/test.cpp.o:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/tests/graphicalTest/test.cpp.o
.PHONY : tests/graphicalTest/test.cpp.o

tests/graphicalTest/test.i: tests/graphicalTest/test.cpp.i

.PHONY : tests/graphicalTest/test.i

# target to preprocess a source file
tests/graphicalTest/test.cpp.i:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/tests/graphicalTest/test.cpp.i
.PHONY : tests/graphicalTest/test.cpp.i

tests/graphicalTest/test.s: tests/graphicalTest/test.cpp.s

.PHONY : tests/graphicalTest/test.s

# target to generate assembly for a file
tests/graphicalTest/test.cpp.s:
	$(MAKE) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/tests/graphicalTest/test.cpp.s
.PHONY : tests/graphicalTest/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Client"
	@echo "... libs/Json/srcs/Entity/Entity.o"
	@echo "... libs/Json/srcs/Entity/Entity.i"
	@echo "... libs/Json/srcs/Entity/Entity.s"
	@echo "... libs/Json/srcs/Parser/Parser.o"
	@echo "... libs/Json/srcs/Parser/Parser.i"
	@echo "... libs/Json/srcs/Parser/Parser.s"
	@echo "... libs/Json/tests/Entity/main.o"
	@echo "... libs/Json/tests/Entity/main.i"
	@echo "... libs/Json/tests/Entity/main.s"
	@echo "... libs/Json/tests/Parser/main.o"
	@echo "... libs/Json/tests/Parser/main.i"
	@echo "... libs/Json/tests/Parser/main.s"
	@echo "... libs/SmartEvent/srcs/Event/Event.o"
	@echo "... libs/SmartEvent/srcs/Event/Event.i"
	@echo "... libs/SmartEvent/srcs/Event/Event.s"
	@echo "... libs/SmartEvent/srcs/HdlCollector/HdlCollector.o"
	@echo "... libs/SmartEvent/srcs/HdlCollector/HdlCollector.i"
	@echo "... libs/SmartEvent/srcs/HdlCollector/HdlCollector.s"
	@echo "... libs/SmartEvent/tests/Event/main.o"
	@echo "... libs/SmartEvent/tests/Event/main.i"
	@echo "... libs/SmartEvent/tests/Event/main.s"
	@echo "... libs/SmartEvent/tests/HdlCollector/main.o"
	@echo "... libs/SmartEvent/tests/HdlCollector/main.i"
	@echo "... libs/SmartEvent/tests/HdlCollector/main.s"
	@echo "... srcs/ECS/Entity/Entity.o"
	@echo "... srcs/ECS/Entity/Entity.i"
	@echo "... srcs/ECS/Entity/Entity.s"
	@echo "... srcs/Graphical/EventReceiver.o"
	@echo "... srcs/Graphical/EventReceiver.i"
	@echo "... srcs/Graphical/EventReceiver.s"
	@echo "... srcs/Graphical/SystemCreateDeletableWall.o"
	@echo "... srcs/Graphical/SystemCreateDeletableWall.i"
	@echo "... srcs/Graphical/SystemCreateDeletableWall.s"
	@echo "... srcs/Graphical/SystemCreateMap.o"
	@echo "... srcs/Graphical/SystemCreateMap.i"
	@echo "... srcs/Graphical/SystemCreateMap.s"
	@echo "... srcs/Graphical/SystemCreatePlayer.o"
	@echo "... srcs/Graphical/SystemCreatePlayer.i"
	@echo "... srcs/Graphical/SystemCreatePlayer.s"
	@echo "... srcs/Graphical/SystemCreateWall.o"
	@echo "... srcs/Graphical/SystemCreateWall.i"
	@echo "... srcs/Graphical/SystemCreateWall.s"
	@echo "... srcs/Graphical/SystemEventManager.o"
	@echo "... srcs/Graphical/SystemEventManager.i"
	@echo "... srcs/Graphical/SystemEventManager.s"
	@echo "... srcs/Graphical/SystemUpdateDeplacement.o"
	@echo "... srcs/Graphical/SystemUpdateDeplacement.i"
	@echo "... srcs/Graphical/SystemUpdateDeplacement.s"
	@echo "... srcs/Main.o"
	@echo "... srcs/Main.i"
	@echo "... srcs/Main.s"
	@echo "... tests/basicECS/Main.o"
	@echo "... tests/basicECS/Main.i"
	@echo "... tests/basicECS/Main.s"
	@echo "... tests/graphicalTest/test.o"
	@echo "... tests/graphicalTest/test.i"
	@echo "... tests/graphicalTest/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

